timeout: 1

/Ferrum Linux
    protocol: linux
    path: boot():/vmlinuz-linux
    cmdline: console=ttyS2,115200n8 root=UUID=placeholder rw virtio_mmio.device=4K@0x400002000:5 virtio_mmio.device=4K@0x400003000:6 virtio_mmio.device=4K@0x400004000:7
    module_path: boot():/initramfs-linux.img