#!/bin/sh

mkdir -p /newroot

mount -t proc proc /proc 2>/dev/null
mount -t sysfs sysfs /sys 2>/dev/null
mount -t devtmpfs devtmpfs /dev 2>/dev/null

while [ ! -b /dev/vda2 ]; do
    echo "waiting for disk..."
    sleep 0.1
done

mount -t ext4 /dev/vda2 /newroot
mount -t proc proc /newroot/proc
mount -t sysfs sysfs /newroot/sys
mount -t devtmpfs devtmpfs /newroot/dev

mkdir -p /newroot/dev/pts
mount -t devpts devpts /newroot/dev/pts

exec </dev/ttyS0 >/dev/ttyS0 2>&1
exec switch_root /newroot /sbin/init

exec /bin/sh
